/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAPayerRouteImport } from './routes/_authenticated/a-payer'
import { Route as AuthenticatedARecevoirRouteImport } from './routes/_authenticated/a-recevoir'
import { Route as AuthenticatedCaisseRouteImport } from './routes/_authenticated/caisse'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPlusRouteImport } from './routes/_authenticated/plus'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedRechercheRouteImport } from './routes/_authenticated/recherche'
import { Route as AuthenticatedRecusRouteImport } from './routes/_authenticated/recus'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedAchatsIndexRouteImport } from './routes/_authenticated/achats.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedDepensesIndexRouteImport } from './routes/_authenticated/depenses.index'
import { Route as AuthenticatedFournisseursIndexRouteImport } from './routes/_authenticated/fournisseurs.index'
import { Route as AuthenticatedProduitsIndexRouteImport } from './routes/_authenticated/produits.index'
import { Route as AuthenticatedVentesIndexRouteImport } from './routes/_authenticated/ventes.index'
import { Route as AuthenticatedVentesIdRouteImport } from './routes/_authenticated/ventes.$id'
import { Route as AuthenticatedVentesNouvelleRouteImport } from './routes/_authenticated/ventes.nouvelle'
import { Route as AuthenticatedVerifierNumberRouteImport } from './routes/_authenticated/verifier.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAPayerRoute = AuthenticatedAPayerRouteImport.update({
  id: '/a-payer',
  path: '/a-payer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedARecevoirRoute = AuthenticatedARecevoirRouteImport.update({
  id: '/a-recevoir',
  path: '/a-recevoir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaisseRoute = AuthenticatedCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlusRoute = AuthenticatedPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechercheRoute = AuthenticatedRechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecusRoute = AuthenticatedRecusRouteImport.update({
  id: '/recus',
  path: '/recus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAchatsIndexRoute =
  AuthenticatedAchatsIndexRouteImport.update({
    id: '/achats/',
    path: '/achats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepensesIndexRoute =
  AuthenticatedDepensesIndexRouteImport.update({
    id: '/depenses/',
    path: '/depenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFournisseursIndexRoute =
  AuthenticatedFournisseursIndexRouteImport.update({
    id: '/fournisseurs/',
    path: '/fournisseurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProduitsIndexRoute =
  AuthenticatedProduitsIndexRouteImport.update({
    id: '/produits/',
    path: '/produits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentesIndexRoute =
  AuthenticatedVentesIndexRouteImport.update({
    id: '/ventes/',
    path: '/ventes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentesIdRoute = AuthenticatedVentesIdRouteImport.update({
  id: '/ventes/$id',
  path: '/ventes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentesNouvelleRoute =
  AuthenticatedVentesNouvelleRouteImport.update({
    id: '/ventes/nouvelle',
    path: '/ventes/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerifierNumberRoute =
  AuthenticatedVerifierNumberRouteImport.update({
    id: '/verifier/$number',
    path: '/verifier/$number',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/a-payer': typeof AuthenticatedAPayerRoute
  '/a-recevoir': typeof AuthenticatedARecevoirRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plus': typeof AuthenticatedPlusRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/recherche': typeof AuthenticatedRechercheRoute
  '/recus': typeof AuthenticatedRecusRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/ventes/$id': typeof AuthenticatedVentesIdRoute
  '/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/verifier/$number': typeof AuthenticatedVerifierNumberRoute
  '/achats/': typeof AuthenticatedAchatsIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/depenses/': typeof AuthenticatedDepensesIndexRoute
  '/fournisseurs/': typeof AuthenticatedFournisseursIndexRoute
  '/produits/': typeof AuthenticatedProduitsIndexRoute
  '/ventes/': typeof AuthenticatedVentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/a-payer': typeof AuthenticatedAPayerRoute
  '/a-recevoir': typeof AuthenticatedARecevoirRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plus': typeof AuthenticatedPlusRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/recherche': typeof AuthenticatedRechercheRoute
  '/recus': typeof AuthenticatedRecusRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/ventes/$id': typeof AuthenticatedVentesIdRoute
  '/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/verifier/$number': typeof AuthenticatedVerifierNumberRoute
  '/achats': typeof AuthenticatedAchatsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/depenses': typeof AuthenticatedDepensesIndexRoute
  '/fournisseurs': typeof AuthenticatedFournisseursIndexRoute
  '/produits': typeof AuthenticatedProduitsIndexRoute
  '/ventes': typeof AuthenticatedVentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/a-payer': typeof AuthenticatedAPayerRoute
  '/_authenticated/a-recevoir': typeof AuthenticatedARecevoirRoute
  '/_authenticated/caisse': typeof AuthenticatedCaisseRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/plus': typeof AuthenticatedPlusRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/recherche': typeof AuthenticatedRechercheRoute
  '/_authenticated/recus': typeof AuthenticatedRecusRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/ventes/$id': typeof AuthenticatedVentesIdRoute
  '/_authenticated/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/_authenticated/verifier/$number': typeof AuthenticatedVerifierNumberRoute
  '/_authenticated/achats/': typeof AuthenticatedAchatsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/depenses/': typeof AuthenticatedDepensesIndexRoute
  '/_authenticated/fournisseurs/': typeof AuthenticatedFournisseursIndexRoute
  '/_authenticated/produits/': typeof AuthenticatedProduitsIndexRoute
  '/_authenticated/ventes/': typeof AuthenticatedVentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/a-payer'
    | '/a-recevoir'
    | '/caisse'
    | '/historique'
    | '/parametres'
    | '/plus'
    | '/rapports'
    | '/recherche'
    | '/recus'
    | '/tableau-de-bord'
    | '/clients/$id'
    | '/ventes/$id'
    | '/ventes/nouvelle'
    | '/verifier/$number'
    | '/achats/'
    | '/clients/'
    | '/depenses/'
    | '/fournisseurs/'
    | '/produits/'
    | '/ventes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/a-payer'
    | '/a-recevoir'
    | '/caisse'
    | '/historique'
    | '/parametres'
    | '/plus'
    | '/rapports'
    | '/recherche'
    | '/recus'
    | '/tableau-de-bord'
    | '/clients/$id'
    | '/ventes/$id'
    | '/ventes/nouvelle'
    | '/verifier/$number'
    | '/achats'
    | '/clients'
    | '/depenses'
    | '/fournisseurs'
    | '/produits'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/a-payer'
    | '/_authenticated/a-recevoir'
    | '/_authenticated/caisse'
    | '/_authenticated/historique'
    | '/_authenticated/parametres'
    | '/_authenticated/plus'
    | '/_authenticated/rapports'
    | '/_authenticated/recherche'
    | '/_authenticated/recus'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/clients/$id'
    | '/_authenticated/ventes/$id'
    | '/_authenticated/ventes/nouvelle'
    | '/_authenticated/verifier/$number'
    | '/_authenticated/achats/'
    | '/_authenticated/clients/'
    | '/_authenticated/depenses/'
    | '/_authenticated/fournisseurs/'
    | '/_authenticated/produits/'
    | '/_authenticated/ventes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/a-payer': {
      id: '/_authenticated/a-payer'
      path: '/a-payer'
      fullPath: '/a-payer'
      preLoaderRoute: typeof AuthenticatedAPayerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/a-recevoir': {
      id: '/_authenticated/a-recevoir'
      path: '/a-recevoir'
      fullPath: '/a-recevoir'
      preLoaderRoute: typeof AuthenticatedARecevoirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caisse': {
      id: '/_authenticated/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof AuthenticatedCaisseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus': {
      id: '/_authenticated/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof AuthenticatedPlusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recherche': {
      id: '/_authenticated/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof AuthenticatedRechercheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recus': {
      id: '/_authenticated/recus'
      path: '/recus'
      fullPath: '/recus'
      preLoaderRoute: typeof AuthenticatedRecusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achats/': {
      id: '/_authenticated/achats/'
      path: '/achats'
      fullPath: '/achats/'
      preLoaderRoute: typeof AuthenticatedAchatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depenses/': {
      id: '/_authenticated/depenses/'
      path: '/depenses'
      fullPath: '/depenses/'
      preLoaderRoute: typeof AuthenticatedDepensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs/': {
      id: '/_authenticated/fournisseurs/'
      path: '/fournisseurs'
      fullPath: '/fournisseurs/'
      preLoaderRoute: typeof AuthenticatedFournisseursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produits/': {
      id: '/_authenticated/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof AuthenticatedProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventes/': {
      id: '/_authenticated/ventes/'
      path: '/ventes'
      fullPath: '/ventes/'
      preLoaderRoute: typeof AuthenticatedVentesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventes/$id': {
      id: '/_authenticated/ventes/$id'
      path: '/ventes/$id'
      fullPath: '/ventes/$id'
      preLoaderRoute: typeof AuthenticatedVentesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventes/nouvelle': {
      id: '/_authenticated/ventes/nouvelle'
      path: '/ventes/nouvelle'
      fullPath: '/ventes/nouvelle'
      preLoaderRoute: typeof AuthenticatedVentesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verifier/$number': {
      id: '/_authenticated/verifier/$number'
      path: '/verifier/$number'
      fullPath: '/verifier/$number'
      preLoaderRoute: typeof AuthenticatedVerifierNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAPayerRoute: typeof AuthenticatedAPayerRoute
  AuthenticatedARecevoirRoute: typeof AuthenticatedARecevoirRoute
  AuthenticatedCaisseRoute: typeof AuthenticatedCaisseRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPlusRoute: typeof AuthenticatedPlusRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedRechercheRoute: typeof AuthenticatedRechercheRoute
  AuthenticatedRecusRoute: typeof AuthenticatedRecusRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedVentesIdRoute: typeof AuthenticatedVentesIdRoute
  AuthenticatedVentesNouvelleRoute: typeof AuthenticatedVentesNouvelleRoute
  AuthenticatedVerifierNumberRoute: typeof AuthenticatedVerifierNumberRoute
  AuthenticatedAchatsIndexRoute: typeof AuthenticatedAchatsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedDepensesIndexRoute: typeof AuthenticatedDepensesIndexRoute
  AuthenticatedFournisseursIndexRoute: typeof AuthenticatedFournisseursIndexRoute
  AuthenticatedProduitsIndexRoute: typeof AuthenticatedProduitsIndexRoute
  AuthenticatedVentesIndexRoute: typeof AuthenticatedVentesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAPayerRoute: AuthenticatedAPayerRoute,
  AuthenticatedARecevoirRoute: AuthenticatedARecevoirRoute,
  AuthenticatedCaisseRoute: AuthenticatedCaisseRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPlusRoute: AuthenticatedPlusRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedRechercheRoute: AuthenticatedRechercheRoute,
  AuthenticatedRecusRoute: AuthenticatedRecusRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedVentesIdRoute: AuthenticatedVentesIdRoute,
  AuthenticatedVentesNouvelleRoute: AuthenticatedVentesNouvelleRoute,
  AuthenticatedVerifierNumberRoute: AuthenticatedVerifierNumberRoute,
  AuthenticatedAchatsIndexRoute: AuthenticatedAchatsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedDepensesIndexRoute: AuthenticatedDepensesIndexRoute,
  AuthenticatedFournisseursIndexRoute: AuthenticatedFournisseursIndexRoute,
  AuthenticatedProduitsIndexRoute: AuthenticatedProduitsIndexRoute,
  AuthenticatedVentesIndexRoute: AuthenticatedVentesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
