/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedProduitsIndexRouteImport } from './routes/_authenticated/produits.index'
import { Route as AuthenticatedVentesIndexRouteImport } from './routes/_authenticated/ventes.index'
import { Route as AuthenticatedVentesIdRouteImport } from './routes/_authenticated/ventes.$id'
import { Route as AuthenticatedVentesNouvelleRouteImport } from './routes/_authenticated/ventes.nouvelle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProduitsIndexRoute =
  AuthenticatedProduitsIndexRouteImport.update({
    id: '/produits/',
    path: '/produits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentesIndexRoute =
  AuthenticatedVentesIndexRouteImport.update({
    id: '/ventes/',
    path: '/ventes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentesIdRoute = AuthenticatedVentesIdRouteImport.update({
  id: '/ventes/$id',
  path: '/ventes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentesNouvelleRoute =
  AuthenticatedVentesNouvelleRouteImport.update({
    id: '/ventes/nouvelle',
    path: '/ventes/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/ventes/$id': typeof AuthenticatedVentesIdRoute
  '/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/produits/': typeof AuthenticatedProduitsIndexRoute
  '/ventes/': typeof AuthenticatedVentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/ventes/$id': typeof AuthenticatedVentesIdRoute
  '/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/produits': typeof AuthenticatedProduitsIndexRoute
  '/ventes': typeof AuthenticatedVentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/ventes/$id': typeof AuthenticatedVentesIdRoute
  '/_authenticated/ventes/nouvelle': typeof AuthenticatedVentesNouvelleRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/produits/': typeof AuthenticatedProduitsIndexRoute
  '/_authenticated/ventes/': typeof AuthenticatedVentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/tableau-de-bord'
    | '/clients/$id'
    | '/ventes/$id'
    | '/ventes/nouvelle'
    | '/clients/'
    | '/produits/'
    | '/ventes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/tableau-de-bord'
    | '/clients/$id'
    | '/ventes/$id'
    | '/ventes/nouvelle'
    | '/clients'
    | '/produits'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/clients/$id'
    | '/_authenticated/ventes/$id'
    | '/_authenticated/ventes/nouvelle'
    | '/_authenticated/clients/'
    | '/_authenticated/produits/'
    | '/_authenticated/ventes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produits/': {
      id: '/_authenticated/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof AuthenticatedProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventes/': {
      id: '/_authenticated/ventes/'
      path: '/ventes'
      fullPath: '/ventes/'
      preLoaderRoute: typeof AuthenticatedVentesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventes/$id': {
      id: '/_authenticated/ventes/$id'
      path: '/ventes/$id'
      fullPath: '/ventes/$id'
      preLoaderRoute: typeof AuthenticatedVentesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventes/nouvelle': {
      id: '/_authenticated/ventes/nouvelle'
      path: '/ventes/nouvelle'
      fullPath: '/ventes/nouvelle'
      preLoaderRoute: typeof AuthenticatedVentesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedVentesIdRoute: typeof AuthenticatedVentesIdRoute
  AuthenticatedVentesNouvelleRoute: typeof AuthenticatedVentesNouvelleRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedProduitsIndexRoute: typeof AuthenticatedProduitsIndexRoute
  AuthenticatedVentesIndexRoute: typeof AuthenticatedVentesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedVentesIdRoute: AuthenticatedVentesIdRoute,
  AuthenticatedVentesNouvelleRoute: AuthenticatedVentesNouvelleRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedProduitsIndexRoute: AuthenticatedProduitsIndexRoute,
  AuthenticatedVentesIndexRoute: AuthenticatedVentesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
